spring:
  application:
    name: jwt
  jwt:
    secret: 1fa82d5d9bd65b86c8052850ce001398
    accessTokenExpiration: 900 # 15m
    refreshTokenExpiration: 604800 # 7d
  
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_db
    username: jwt_user
    password: jwt_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        
    
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/jwt_db
    user: jwt_user
    password: jwt_password

server:
  port: 8087

